/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {

    @BeforeMethod
    @Parameters({"mobile"})
    void setup(@Optional("Not found") String mobile){
        System.out.println(mobile);
    }
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
